name: Playwright Tests
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Set environment variable for deployed site
      run: echo "NEXT_PUBLIC_WEB_SERVER_URL=https://www.ticktopia.shop" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Seed API data (GET)
      run: |
        curl https://back.ticktopia.shop/api/seed

    - name: Run Playwright tests against deployed site
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30